jsf3.validator("validate01",{

    rules:{
        required:[
            {
                rule:"required",
                message:"requiredが空です",
            },
        ],
        required_if:[
            {
                rule:["requiredIf","required_if_2",1],
                message:"required_ifが未入力です",
            },
        ],
        required_with:[
            {
                rule:["requiredWith",["required_with_2","required_with_3"]],
                message:"1つめを必ず入力してください",
            },
        ],
        required_withor:[
            {
                rule:["requiredWithOr",["required_withor_2","required_withor_3"]],
                message:"1つめを必ず入力してください",
            },
        ],
        confirmed:[
            {
                rule:["confirmed","confirmed_2"],
                message:"上下ともに同じ値を入力してください",
            },
        ],
        alpha_numeric:[
            {
                rule:["alphaNumeric",".-,"],
                message:"半角英数字で入力して下さい(「.」「-」「,」は可能)",
            },
        ],
        numeric:[
            {
                rule:["numeric",".-,"],
                message:"半角数字で入力して下さい(「.」「-」「,」は可能)",
            }
        ],

        length:[
            {
                rule:["length",6],
                message:"6文字で入力してください",
            },
        ],
        minLength:[
            {
                rule:["minLength",4],
                message:"4文字以上で入力してください",
            },
        ],
        maxLength:[
            {
                rule:["maxLength",16],
                message:"16文字以内で入力してください",
            },
        ],
        betweenLength:[
            {
                rule:["betweenLength",3,7],
                message:"3～7文字で入力してください",
            },
        ],
        value:[
            {
                rule:["value",6],
                message:"6を入力してください",
            },
        ],
        minValue:[
            {
                rule:["minValue",3],
                message:"3以上を入力してください",
            },
        ],
        maxValue:[
            {
                rule:["maxValue",10],
                message:"10以下を入力してください",
            },
        ],
        betweenValue:[
            {
                rule:["betweenValue",3,10],
                message:"3～10を入力してください",
            },
        ],

        selectedCount:[
            {
                rule:["selectedCount",3],
                message:"3つ必ず選択してください",
            },
        ],
        minSelectedCount:[
            {
                rule:["minSelectedCount",3],
                message:"3つ以上を必ず選択してください",
            },
        ],
        maxSelectedCount:[
            {
                rule:["maxSelectedCount",5],
                message:"選択できるのは5つまでです",
            },
        ],
        betweenSelectedCount:[
            {
                rule:["betweenSelectedCount",2,5],
                message:"2～5個の範囲で選択してください",
            },
        ],


    },


});